const userActionTypes = {
	SET_CURRENT_USER: ' SET_CURRENT_USER',
	GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START ',
	SIGNIN_SUCCESS: 'GOOGLE_SIGNIN_SUCCESS ',
	SIGNIN_FAILURE: 'GOOGLE_SIGNIN_FAILURE ',
	EMAIL_SIGNIN_START: ' EMAIL_SIGNIN_START',
};

export default userActionTypes;
